-- ==============================================================================
-- PHARMAVITA / CLINICALRX - SUPABASE DATABASE SCHEMA V3
-- Hệ thống Thông tin Thuốc & Dược Lâm Sàng
-- Tuân thủ bảo mật y tế & phân quyền vai trò (Role-Based Access Control)
-- ==============================================================================

-- 1. BẢNG HỒ SƠ NGƯỜI DÙNG (PROFILES)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null,
  role text not null default 'Bác sĩ' check (role in ('Bác sĩ', 'Dược sĩ lâm sàng', 'Điều dưỡng', 'Admin')),
  department text,             -- Khoa / Phòng lâm sàng (VD: Hồi sức tích cực, Tim mạch...)
  license_number text,         -- Số chứng chỉ hành nghề y/dược (nếu có)
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. BẢNG YÊU CẦU TƯ VẤN & HỎI ĐÁP THÔNG TIN THUỐC (CONSULTATIONS / QUESTIONS)
create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  doctor_id uuid not null references public.profiles(id) on delete cascade,
  pharmacist_id uuid references public.profiles(id),
  title text not null,
  category text not null default 'Chỉnh liều' check (
    category in ('Chỉnh liều suy thận/gan', 'Tương tác thuốc', 'Tương kỵ tiêm truyền', 'Phụ nữ mang thai/cho con bú', 'Tác dụng không mong muốn (ADR)', 'Lựa chọn phác đồ', 'Khác')
  ),
  urgency text not null default 'Thường quy' check (urgency in ('Khẩn cấp (< 1 giờ)', 'Bình thường (< 4 giờ)', 'Thường quy (trong ngày)')),
  
  -- Thông tin lâm sàng ca bệnh (Phi định danh - An toàn bảo mật)
  patient_age integer,
  patient_gender text check (patient_gender in ('Nam', 'Nữ', 'Khác')),
  patient_weight numeric(5,2),  -- kg
  patient_creatinine numeric(5,2), -- mg/dL hoặc umol/L
  clinical_diagnosis text,     -- Chẩn đoán lâm sàng
  current_medications text,    -- Các thuốc đang dùng
  inquiry_content text not null, -- Nội dung câu hỏi chi tiết
  
  -- Phản hồi của Dược sĩ lâm sàng
  pharmacist_answer text,      -- Nội dung trả lời theo chuẩn y học chứng cứ (EBM)
  references_text text,        -- Tài liệu tham khảo (Dược thư QG, Uptodate, Micromedex...)
  
  status text not null default 'pending' check (
    status in ('pending', 'in_progress', 'answered', 'closed')
  ),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  updated_at timestamptz not null default now()
);

-- 3. BẢNG BÁO CÁO PHẢN ỨNG CÓ HẠI CỦA THUỐC (ADR REPORTS)
create table if not exists public.adr_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  patient_code text not null,  -- Mã hồ sơ bệnh án (không lưu tên đầy đủ)
  patient_age integer,
  patient_gender text,
  patient_weight numeric(5,2),
  
  suspected_drug text not null,-- Tên thuốc nghi ngờ gây ADR
  dosage_and_route text,       -- Liều dùng & đường dùng
  indication text,             -- Chỉ định dùng thuốc
  reaction_description text not null, -- Mô tả biến cố phản ứng có hại
  reaction_onset timestamptz,  -- Thời điểm xuất hiện
  
  severity text not null default 'Nghiêm trọng' check (
    severity in ('Tử vong', 'Đe dọa tính mạng', 'Nhập viện/Kéo dài nằm viện', 'Dị tật bẩm sinh', 'Để lại di chứng', 'Không nghiêm trọng')
  ),
  outcome text check (
    outcome in ('Hồi phục hoàn toàn', 'Đang hồi phục', 'Chưa hồi phục', 'Tử vong do ADR', 'Tử vong không do ADR', 'Không rõ')
  ),
  dechallenge text check (dechallenge in ('Giảm sau ngừng thuốc', 'Không giảm', 'Không ngừng/Không rõ')),
  rechallenge text check (rechallenge in ('Tái phát khi dùng lại', 'Không tái phát', 'Không dùng lại')),
  
  causality_assessment text,   -- Thang đánh giá Naranjo hoặc WHO
  created_at timestamptz not null default now()
);

-- KÍCH HOẠT ROW LEVEL SECURITY (RLS) ĐẢM BẢO BẢO MẬT
alter table public.profiles enable row level security;
alter table public.consultations enable row level security;
alter table public.adr_reports enable row level security;

-- CHÍNH SÁCH BẢO MẬT (RLS POLICIES)
-- Profiles: Người dùng xem được thông tin của đồng nghiệp trong hệ thống, chỉ sửa profile của chính mình
drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles" on public.profiles 
  for select to authenticated using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles 
  for update to authenticated using (id = auth.uid());

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles 
  for insert to authenticated with check (id = auth.uid());

-- Consultations: 
-- 1. Bác sĩ xem được ca bệnh do mình tạo. Dược sĩ & Admin xem được tất cả ca bệnh để tiếp nhận và phản hồi.
drop policy if exists "Doctor or Pharmacist read consultations" on public.consultations;
create policy "Doctor or Pharmacist read consultations" on public.consultations
  for select to authenticated 
  using (
    doctor_id = auth.uid() 
    or pharmacist_id = auth.uid() 
    or exists (select 1 from public.profiles where id = auth.uid() and role in ('Dược sĩ lâm sàng', 'Admin'))
  );

drop policy if exists "Doctor can create consultation" on public.consultations;
create policy "Doctor can create consultation" on public.consultations
  for insert to authenticated with check (doctor_id = auth.uid());

drop policy if exists "Doctor can update own pending consultation" on public.consultations;
create policy "Doctor can update own pending consultation" on public.consultations
  for update to authenticated 
  using (
    doctor_id = auth.uid() 
    or exists (select 1 from public.profiles where id = auth.uid() and role in ('Dược sĩ lâm sàng', 'Admin'))
  );

-- ADR Reports: Bác sĩ/Dược sĩ có thể gửi và xem báo cáo ADR của viện
drop policy if exists "Authenticated users can view ADR" on public.adr_reports;
create policy "Authenticated users can view ADR" on public.adr_reports 
  for select to authenticated using (true);

drop policy if exists "Authenticated users can insert ADR" on public.adr_reports;
create policy "Authenticated users can insert ADR" on public.adr_reports 
  for insert to authenticated with check (reporter_id = auth.uid());

-- TRIGGER TỰ ĐỘNG TẠO PROFILE KHI ĐĂNG KÝ USER MỚI
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, department)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'Bác sĩ'),
    coalesce(new.raw_user_meta_data->>'department', 'Nội trú')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ==============================================================================
-- 4. BẢNG DƯỢC THƯ NỘI VIỆN & THUỐC TÙY BIẾN ĐỒNG BỘ ĐÁM MÂY (CUSTOM DRUGS)
-- ==============================================================================
create table if not exists public.custom_drugs (
  id text primary key,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.custom_drugs enable row level security;

drop policy if exists "Public read custom_drugs" on public.custom_drugs;
create policy "Public read custom_drugs" on public.custom_drugs
  for select using (true);

drop policy if exists "Allow insert custom_drugs" on public.custom_drugs;
create policy "Allow insert custom_drugs" on public.custom_drugs
  for insert with check (true);

drop policy if exists "Allow update custom_drugs" on public.custom_drugs;
create policy "Allow update custom_drugs" on public.custom_drugs
  for update using (true);

drop policy if exists "Allow delete custom_drugs" on public.custom_drugs;
create policy "Allow delete custom_drugs" on public.custom_drugs
  for delete using (true);

grant all on public.custom_drugs to anon, authenticated, service_role;

-- ==============================================================================
-- 5. KHO LƯU TRỮ FILE PDF THUỐC ĐỒNG BỘ ĐÁM MÂY (SUPABASE STORAGE: drug-pdfs)
-- Cho phép tải lên và xem tài liệu PDF trực tuyến giữa mọi máy tính và điện thoại
-- ==============================================================================
insert into storage.buckets (id, name, public)
values ('drug-pdfs', 'drug-pdfs', true)
on conflict (id) do update set public = true;

drop policy if exists "Public read drug-pdfs" on storage.objects;
create policy "Public read drug-pdfs" on storage.objects for select using (bucket_id = 'drug-pdfs');

drop policy if exists "Public insert drug-pdfs" on storage.objects;
create policy "Public insert drug-pdfs" on storage.objects for insert with check (bucket_id = 'drug-pdfs');

drop policy if exists "Public update drug-pdfs" on storage.objects;
create policy "Public update drug-pdfs" on storage.objects for update using (bucket_id = 'drug-pdfs');

drop policy if exists "Public delete drug-pdfs" on storage.objects;
create policy "Public delete drug-pdfs" on storage.objects for delete using (bucket_id = 'drug-pdfs');
